/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_header = 1,
  sym_comment = 2,
  aux_sym_list_item_token1 = 3,
  aux_sym_list_item_token2 = 4,
  sym_list_marker = 5,
  aux_sym_pair_token1 = 6,
  sym_separator = 7,
  sym_value = 8,
  sym__blank = 9,
  sym__eol = 10,
  sym_key = 11,
  sym_continuation = 12,
  sym__error_sentinel = 13,
  sym_document = 14,
  sym_list_item = 15,
  sym_pair = 16,
  aux_sym_document_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_header] = "header",
  [sym_comment] = "comment",
  [aux_sym_list_item_token1] = "list_item_token1",
  [aux_sym_list_item_token2] = "list_item_token2",
  [sym_list_marker] = "list_marker",
  [aux_sym_pair_token1] = "pair_token1",
  [sym_separator] = "separator",
  [sym_value] = "value",
  [sym__blank] = "_blank",
  [sym__eol] = "_eol",
  [sym_key] = "key",
  [sym_continuation] = "continuation",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym_list_item] = "list_item",
  [sym_pair] = "pair",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_header] = sym_header,
  [sym_comment] = sym_comment,
  [aux_sym_list_item_token1] = aux_sym_list_item_token1,
  [aux_sym_list_item_token2] = aux_sym_list_item_token2,
  [sym_list_marker] = sym_list_marker,
  [aux_sym_pair_token1] = aux_sym_pair_token1,
  [sym_separator] = sym_separator,
  [sym_value] = sym_value,
  [sym__blank] = sym__blank,
  [sym__eol] = sym__eol,
  [sym_key] = sym_key,
  [sym_continuation] = sym_continuation,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym_list_item] = sym_list_item,
  [sym_pair] = sym_pair,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_list_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_item_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_list_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_marker = 2,
  field_separator = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_marker] = "marker",
  [field_separator] = "separator",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_separator, 2},
  [2] =
    {field_marker, 1},
    {field_value, 3},
  [4] =
    {field_key, 0},
    {field_separator, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_list_item_token1);
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(2);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'k') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'v') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_header);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_list_item_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_list_item_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_list_item_token1);
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_list_item_token2);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_list_marker);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__blank);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 23, .external_lex_state = 2},
  [2] = {.lex_state = 23, .external_lex_state = 2},
  [3] = {.lex_state = 23, .external_lex_state = 2},
  [4] = {.lex_state = 23, .external_lex_state = 2},
  [5] = {.lex_state = 23, .external_lex_state = 2},
  [6] = {.lex_state = 23, .external_lex_state = 2},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_list_item_token1] = ACTIONS(1),
    [aux_sym_list_item_token2] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [sym_continuation] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(10),
    [sym_list_item] = STATE(2),
    [sym_pair] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_header] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [aux_sym_list_item_token1] = ACTIONS(7),
    [sym__blank] = ACTIONS(5),
    [sym_key] = ACTIONS(9),
    [sym_continuation] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_list_item] = STATE(3),
    [sym_pair] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_header] = ACTIONS(13),
    [sym_comment] = ACTIONS(13),
    [aux_sym_list_item_token1] = ACTIONS(7),
    [sym__blank] = ACTIONS(13),
    [sym_key] = ACTIONS(9),
    [sym_continuation] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_list_item] = STATE(3),
    [sym_pair] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_header] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
    [aux_sym_list_item_token1] = ACTIONS(20),
    [sym__blank] = ACTIONS(17),
    [sym_key] = ACTIONS(23),
    [sym_continuation] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(28), 1,
      aux_sym_list_item_token1,
    ACTIONS(26), 6,
      sym_key,
      sym_continuation,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      sym__blank,
  [12] = 2,
    ACTIONS(32), 1,
      aux_sym_list_item_token1,
    ACTIONS(30), 6,
      sym_key,
      sym_continuation,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      sym__blank,
  [24] = 2,
    ACTIONS(36), 1,
      aux_sym_list_item_token1,
    ACTIONS(34), 6,
      sym_key,
      sym_continuation,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      sym__blank,
  [36] = 2,
    ACTIONS(38), 1,
      aux_sym_pair_token1,
    ACTIONS(40), 1,
      sym__eol,
  [43] = 1,
    ACTIONS(42), 1,
      aux_sym_list_item_token1,
  [47] = 1,
    ACTIONS(44), 1,
      sym_list_marker,
  [51] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [55] = 1,
    ACTIONS(48), 1,
      sym_separator,
  [59] = 1,
    ACTIONS(50), 1,
      aux_sym_list_item_token2,
  [63] = 1,
    ACTIONS(52), 1,
      sym_value,
  [67] = 1,
    ACTIONS(54), 1,
      sym_value,
  [71] = 1,
    ACTIONS(56), 1,
      sym__eol,
  [75] = 1,
    ACTIONS(58), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 24,
  [SMALL_STATE(7)] = 36,
  [SMALL_STATE(8)] = 43,
  [SMALL_STATE(9)] = 47,
  [SMALL_STATE(10)] = 51,
  [SMALL_STATE(11)] = 55,
  [SMALL_STATE(12)] = 59,
  [SMALL_STATE(13)] = 63,
  [SMALL_STATE(14)] = 67,
  [SMALL_STATE(15)] = 71,
  [SMALL_STATE(16)] = 75,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 4, 0, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 5, 0, 2),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 5, 0, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 6, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 6, 0, 3),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_key = 0,
  ts_external_token_continuation = 1,
  ts_external_token__error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_key] = sym_key,
  [ts_external_token_continuation] = sym_continuation,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_key] = true,
    [ts_external_token_continuation] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_key] = true,
    [ts_external_token_continuation] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_kvl_external_scanner_create(void);
void tree_sitter_kvl_external_scanner_destroy(void *);
bool tree_sitter_kvl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_kvl_external_scanner_serialize(void *, char *);
void tree_sitter_kvl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kvl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_kvl_external_scanner_create,
      tree_sitter_kvl_external_scanner_destroy,
      tree_sitter_kvl_external_scanner_scan,
      tree_sitter_kvl_external_scanner_serialize,
      tree_sitter_kvl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "kvl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
